import Head from "next/head";
import { Row, Col, Image, Container, Navbar, Nav, Form, FormControl, Button } from 'react-bootstrap';
import { useRouter } from 'next/router'; // Import useRouter for routing
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter(); // Initialize useRouter hook
  const handleSearch = (e) => {
    e.preventDefault();
    const query = e.target.search.value; // Get the search query
    if (query) {
      router.push(`/artwork?title=true&q=${encodeURIComponent(query)}`); // Redirect to artwork page with query
    }
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar bg="primary" variant="dark" expand="lg" fixed="top">
        <Container>
          <Navbar.Brand>Jacob Rivera</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="me-auto">
              <Nav.Link href="/">Home</Nav.Link>
              <Nav.Link href="/search">Advanced Search</Nav.Link>
            </Nav>
            {/* Updated Form with handleSearch on submit */}
            <Form className="d-flex" onSubmit={handleSearch}>
              <FormControl
                type="search"
                name="search"
                placeholder="Search"
                className="me-2"
                aria-label="Search"
              />
              <Button variant="success" type="submit">Search</Button>
            </Form>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <br /><br /><br /><br />
      <Container>
        <Row>
          <Col>
            <Image 
              src="https://upload.wikimedia.org/wikipedia/commons/3/30/Metropolitan_Museum_of_Art_%28The_Met%29_-_Central_Park%2C_NYC.jpg" 
              fluid 
              rounded 
              alt="MET Building"
              className="img-fluid"
            />
            <br /><br />
          </Col>
        </Row>
        <Row>
          <Col lg={6}>
            <p>
              The Metropolitan Museum of Art of New York City, colloquially "the Met", is the largest art museum in the Americas. Its permanent collection contains over two million works, divided among 17 curatorial departments. The main building at 1000 Fifth Avenue, along the Museum Mile on the eastern edge of Central Park on Manhattan's Upper East Side, is by area one of the world's largest art museums. A much smaller second location, The Cloisters at Fort Tryon Park in Upper Manhattan, contains an extensive collection of art, architecture, and artifacts from medieval Europe.
            </p>
            <p>
              The Metropolitan Museum of Art was founded in 1870 with its mission to bring art and art education to the American people. The museum's permanent collection consists of works of art from classical antiquity and ancient Egypt, paintings, and sculptures from nearly all the European masters, and an extensive collection of American and modern art. The Met maintains extensive holdings of African, Asian, Oceanian, Byzantine, and Islamic art. The museum is home to encyclopedic collections of musical instruments, costumes, and accessories, as well as antique weapons and armor from around the world. Several notable interiors, ranging from 1st-century Rome through modern American design, are installed in its galleries.
            </p>
          </Col>
          <Col lg={6}>
            <p>
              The Fifth Avenue building opened on March 30, 1880. In 2021, despite the COVID-19 pandemic in New York City, the museum attracted 1,958,000 visitors, ranking fourth on the list of most-visited art museums in the world.
            </p>
            <p>
              <a href="https://en.wikipedia.org/wiki/Metropolitan_Museum_of_Art" target="_blank" rel="noreferrer">https://en.wikipedia.org/wiki/Metropolitan_Museum_of_Art</a>
            </p>
          </Col>
        </Row>
      </Container>
    </>
  );
}